In [61]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import yfinance as yf

In [2]:
def get_brand_name ():

    url = 'https://www.lyst.com/the-lyst-index/the-lyst-index-q2-25/'
    r = requests.get(url)
    soup = BeautifulSoup(r.content)
    grid = soup.find('div', attrs = {'class':'chart-update'})
    brand_elements = grid.find_all('div', attrs = {'class':'mono-type padding-left'})

    brand_names = []
    
    for elements in brand_elements:
          clean_brand_name = elements.get_text()
          brand_names.append(clean_brand_name)

    return brand_names

In [ ]:
get_brand_name()

['MIU MIU',
 'LOEWE',
 'SAINT LAURENT',
 'PRADA',
 'COACH',
 'THE ROW',
 'COS',
 'CHLOÉ',
 'Bottega Veneta',
 'Moncler',
 'Ralph Lauren',
 'ALAÏA',
 'Balenciaga',
 'JACQUEMUS',
 'SKIMS',
 'Versace',
 'BURBERRY',
 'GUCCI',
 'Birkenstock',
 'VALENTINO']

In [67]:
company_names = pd.read_csv('fashion_brands_parent_companies.csv')
company_names = pd.DataFrame(company_names)
company_names

,Brand,ParentCompany,Ticker,SourceURL
0,MIU MIU,Prada Group,PRDSF,https://www.pradagroup.com/en/brands/miu-miu.html
1,LOEWE,LVMH,MC.PA,https://www.lvmh.com/en/our-maisons/fashion-le...
2,SAINT LAURENT,Kering,KER.PA,https://www.kering.com/en/houses/couture-and-l...
3,PRADA,Prada Group,PRDSF,https://www.pradagroup.com/en/brands/prada.html
4,COACH,Tapestry Inc.,TPR,https://www.tapestry.com/our-brands/coach/
5,THE ROW,Private (Dualstar / Olsen twins),NaN,https://therow.com/pages/about
6,COS,H&M Group,OM:HM B,https://hmgroup.com/brands/cos/
7,CHLOÉ,Richemont,CFR.SW,https://www.richemont.com/en/maison/chloe/
8,Bottega Veneta,Kering,KER.PA,https://www.kering.com/en/houses/couture-and-l...
9,Moncler,Moncler S.p.A.,MOV.F,https://www.monclergroup.com/en/brands/moncler
10,Ralph Lauren,Ralph Lauren Corporation,RL,https://corporate.ralphlauren.com/
11,ALAÏA,Richemont,CFR.SW,https://www.richemont.com/en/maison/alaia/
12,Balenciaga,Kering,KER.PA,https://www.kering.com/en/houses/couture-and-l...
13,JACQUEMUS,Private (Simon Porte Jacquemus),NaN,https://www.jacquemus.com/
14,SKIMS,Private (Kim Kardashian & Investors),NaN,https://www.skims.com/pages/about-skims
15,Versace,Capri Holdings Limited,CPRI,https://www.capriholdings.com/versace/
16,BURBERRY,Burberry Group plc,BBRYF,https://www.burberryplc.com/en/brands.html
17,GUCCI,Kering,KER.PA,https://www.kering.com/en/houses/couture-and-l...
18,Birkenstock,L Catterton / Financière Agache,NaN,https://www.birkenstock-group.com/en/company/
19,VALENTINO,Mayhoola for Investments,NaN,https://www.valentino.com/en-int/about-valentino/

In [68]:
company_names_2 = company_names.drop('SourceURL', axis=1)
company_names_2

             Brand                         ParentCompany   Ticker
0          MIU MIU                           Prada Group    PRDSF
1            LOEWE                                  LVMH    MC.PA
2    SAINT LAURENT                                Kering   KER.PA
3            PRADA                           Prada Group    PRDSF
4            COACH                         Tapestry Inc.      TPR
5          THE ROW      Private (Dualstar / Olsen twins)      NaN
6              COS                             H&M Group  OM:HM B
7            CHLOÉ                             Richemont   CFR.SW
8   Bottega Veneta                                Kering   KER.PA
9          Moncler                        Moncler S.p.A.    MOV.F
10    Ralph Lauren              Ralph Lauren Corporation       RL
11           ALAÏA                             Richemont   CFR.SW
12      Balenciaga                                Kering   KER.PA
13       JACQUEMUS       Private (Simon Porte Jacquemus)      NaN
14           SKIMS  Private (Kim Kardashian & Investors)      NaN
15         Versace                Capri Holdings Limited     CPRI
16        BURBERRY                    Burberry Group plc    BBRYF
17           GUCCI                                Kering   KER.PA
18     Birkenstock       L Catterton / Financière Agache      NaN
19       VALENTINO              Mayhoola for Investments      NaN

In [69]:
grouped = company_names_2.groupby(['ParentCompany', 'Ticker','Brand']).count().reset_index()
grouped

               ParentCompany   Ticker           Brand
0         Burberry Group plc    BBRYF        BURBERRY
1     Capri Holdings Limited     CPRI         Versace
2                  H&M Group  OM:HM B             COS
3                     Kering   KER.PA      Balenciaga
4                     Kering   KER.PA  Bottega Veneta
5                     Kering   KER.PA           GUCCI
6                     Kering   KER.PA   SAINT LAURENT
7                       LVMH    MC.PA           LOEWE
8             Moncler S.p.A.    MOV.F         Moncler
9                Prada Group    PRDSF         MIU MIU
10               Prada Group    PRDSF           PRADA
11  Ralph Lauren Corporation       RL    Ralph Lauren
12                 Richemont   CFR.SW           ALAÏA
13                 Richemont   CFR.SW           CHLOÉ
14             Tapestry Inc.      TPR           COACH

In [85]:
grouped = grouped.groupby(['ParentCompany', 'Ticker'])['Brand'].apply(', '.join).reset_index()
grouped

,ParentCompany,Ticker,Brand
0,Burberry Group plc,BBRYF,BURBERRY
1,Capri Holdings Limited,CPRI,Versace
2,H&M Group,OM:HM B,COS
3,Kering,KER.PA,"Balenciaga, Bottega Veneta, GUCCI, SAINT LAURENT"
4,LVMH,MC.PA,LOEWE
5,Moncler S.p.A.,MOV.F,Moncler
6,Prada Group,PRDSF,"MIU MIU, PRADA"
7,Ralph Lauren Corporation,RL,Ralph Lauren
8,Richemont,CFR.SW,"ALAÏA, CHLOÉ"
9,Tapestry Inc.,TPR,COACH

In [ ]:
# Get financel data

In [79]:
dat = yf.Ticker("BBRYF")
dat

yfinance.Ticker object <BBRYF>

In [84]:
dat = yf.Ticker("BBRYF")
#dat.info
#dat.analyst_price_targets
dat.history(period='5y')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-10-21 00:00:00-04:00,17.328339,17.328339,17.328339,17.328339,0,0.0,0.0
2020-10-22 00:00:00-04:00,17.328339,17.328339,17.328339,17.328339,0,0.0,0.0
2020-10-23 00:00:00-04:00,17.328339,17.328339,17.328339,17.328339,0,0.0,0.0
2020-10-26 00:00:00-04:00,17.328339,17.328339,17.328339,17.328339,0,0.0,0.0
2020-10-27 00:00:00-04:00,15.979899,15.979899,15.944874,15.944874,1000,0.0,0.0
...,...,...,...,...,...,...,...
2025-10-14 00:00:00-04:00,16.740000,16.740000,16.740000,16.740000,0,0.0,0.0
2025-10-15 00:00:00-04:00,16.320000,16.320000,16.320000,16.320000,100,0.0,0.0
2025-10-16 00:00:00-04:00,16.320000,16.320000,16.320000,16.320000,0,0.0,0.0
2025-10-17 00:00:00-04:00,16.320000,16.320000,16.320000,16.320000,0,0.0,0.0
2025-10-20 00:00:00-04:00,16.690001,16.690001,16.690001,16.379999,500,0.0,0.0